field.widget.settings.revision_log_widget:
  type: mapping
  label: 'Revision Log Widget settings.'
  mapping:
    rows:
      type: integer
      label: 'Rows'
    placeholder:
      type: label
      label: 'Placeholder'
    default:
      type: label
      label: 'Default value'
    display_mode:
      type: string
      label: 'Display field'
    collapsed:
      type: boolean
      label: 'Collapses the field by default'
